export {
  orderSlice,
  selectIsStatesDeliveryTub,
  selectIsStatesTypePayment,
  toggleStateTabs,
  setStateTabs,
  setMapOrder,
  selectMapOrder,
  selectIsLoadListGeoDataOffice,
  setLoadListGeoDataOffice,
  setChooseOfficeAddress,
  selectChooseOfficeAddress,
  selectOfficeGeoData,
  selectIsLoadingOfficeGeoData,
  setChooseAddressCourier,
  selectIsChooseCourierAddress,
  getOfficeByCity,
  selectOpenMapModal,
  setIsMapModalOpen,
  setShowCourierAddressData,
  selectShowCourierAddressData,
} from "./slice";
